In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
np.set_printoptions(suppress=True)

In [17]:
# Scalar
scalar = 5.0
print(scalar)

# Vector
vector = np.array(
    [3,7,2]
)
print(vector)
print("Shape:", vector.shape)

# Matrix
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print("Matrix:", matrix)
print("Shape:", matrix.shape)


# Tensor
tensor = np.array([
    [
        [1,2,3],
        [4,5,6],
    ],
    [
        [11,12,13],
        [14,15,16]
    ]
])

print("Tensor:", tensor)
print("Shape:", tensor.shape)

5.0
[3 7 2]
Shape: (3,)
Matrix: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
Shape: (2, 2, 3)


In [19]:
# 3 samples and 2 features
# feature 1: hours of studied
# feature 2: number of practice question
# target: (1) passed | (0) failed

x = np.array(
    [
        [2,30],
        [5,80],
        [1,20]
    ]
)

y = np.array([0, 1, 0])

In [32]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print("v1:", v1)
print("v2:", v2)
vector_add = v1 + v2
print("Add:",vector_add)
vector_multi = v1 * v2
print("Multi:",vector_multi)

A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [10,11,12],
    [13,14,15]
])

C = np.array([
    [1,2,3],
    [3,4,5],
    [6,7,9]
])

print(f"Shape A: {A.shape} B: {B.shape}")
A_add_B = A + B
print("A + B:", A_add_B)
A_T = A.T
print("A Transpose: ", A_T)
C_X = np.linalg.inv(C)
print("A inverse:", C_X)

v1: [1 2 3 4]
v2: [5 6 7 8]
Add: [ 6  8 10 12]
Multi: [ 5 12 21 32]
Shape A: (2, 3) B: (2, 3)
A + B: [[11 13 15]
 [17 19 21]]
A Transpose:  [[1 4]
 [2 5]
 [3 6]]
A inverse: [[-0.5 -1.5  1. ]
 [-1.5  4.5 -2. ]
 [ 1.5 -2.5  1. ]]


In [33]:
v1 = np.array([1,2])
v2 = np.array([3,4])
dot = np.dot(v1,v2)
print("Dot:", dot)

Dot: 11


In [36]:
diff = v1 - v2
print("Diff:", diff)

Diff: [-2 -2]


In [38]:
distance = np.linalg.norm(diff)
print("Euclidean distance between v1 and v2:", distance)

Euclidean distance between v1 and v2: 2.8284271247461903


In [39]:
# Matrix Multiplication and Linear Model

X = np.array([
    [1.0, 30.0],
    [2.0, 50.0],
    [3.0, 70.0]
])

print("X:\n", X)
print("X shape:", X.shape)

X:
 [[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]
X shape: (3, 2)


In [41]:
w = np.array([
    [0.5],
    [0.1]
])

print("Weight Shape:", w.shape)

Weight Shape: (2, 1)


In [43]:
# formula: y = wX + b
Xw = X @ w
print("Xw:\n", Xw)

Xw:
 [[3.5]
 [6. ]
 [8.5]]


In [45]:
b = 2.0
y = Xw + b
print("y = Xw + b:\n", y)

y = Xw + b:
 [[ 5.5]
 [ 8. ]
 [10.5]]


In [46]:
# Connecting this to a sample dataset
data = np.array([
    [85, 26.6, 31, 0],
    [183, 23.3, 32, 1],
    [89, 28.1, 21, 0],
    [137, 43.1, 33, 1],
])

print("Full data matrix:\n", data)
print("Data shape:", data.shape)



Full data matrix:
 [[ 85.   26.6  31.    0. ]
 [183.   23.3  32.    1. ]
 [ 89.   28.1  21.    0. ]
 [137.   43.1  33.    1. ]]
Data shape: (4, 4)


In [56]:
X_features = data[:,:-1]
Y_target = data[:,-1]
test = "ABC"
print("Features:\n",X_features)
print("Target:",Y_target)

AB
Features:
 [[ 85.   26.6  31. ]
 [183.   23.3  32. ]
 [ 89.   28.1  21. ]
 [137.   43.1  33. ]]
Target: [0. 1. 0. 1.]
