### NumPy Basic Project/Assignment: Linear Algebra Fundamentals

**Objective:** This project aims to reinforce your understanding of fundamental linear algebra operations using NumPy arrays, specifically focusing on vectors and matrices.

---

#### Provided Dataset:

For this assignment, you will work with the following vectors and matrices. You will need to create NumPy arrays from these values.

```
vector_u_list = [1, 2, 3]
vector_v_list = [4, 5, 6]

matrix_A_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_B_list = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]
```

#### Task 1: Vector and Matrix Creation

**Objective:** Initialize NumPy arrays for the given vectors and matrices.

**Your Task:**
1.  Import the NumPy library.
2.  Create NumPy 1D arrays (vectors) `u` and `v` from `vector_u_list` and `vector_v_list`, respectively.
3.  Create NumPy 2D arrays (matrices) `A` and `B` from `matrix_A_list` and `matrix_B_list`, respectively.
4.  Print the shape and number of dimensions for each created array.

#### Task 2: Vector Operations

**Objective:** Perform common vector operations.

**Your Task:**
1.  Calculate the element-wise sum of `u` and `v`.
2.  Calculate the dot product of `u` and `v`.
3.  Calculate the magnitude (L2 norm) of vector `u`.

#### Task 3: Matrix Operations

**Objective:** Perform basic matrix operations.

**Your Task:**
1.  Calculate the element-wise sum of matrices `A` and `B`.
2.  Calculate the matrix product of `A` and `B` (i.e., A multiplied by B).
3.  Calculate the transpose of matrix `A`.
4.  Find the determinant of matrix `A`.

#### Task 4: Advanced Matrix Operations (Inverse and Solving Linear Systems)

**Objective:** Explore more advanced matrix functionalities.

**Your Task:**
1.  Try to calculate the inverse of matrix `A`. (Be aware that not all matrices have an inverse; if it fails, note down the error).
2.  Given a new vector `b_vec = [10, 20, 30]`, solve the linear system `Ax = b_vec` for `x`. (This is an optional challenge, as `A` might be singular based on the example data provided, but try to use NumPy's linear algebra functions to attempt it.)

In [3]:
import numpy as np

In [5]:
vector_u_list = [1, 2, 3]
vector_v_list = [4, 5, 6]

matrix_A_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_B_list = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

In [12]:
# Task 1

oned_arr_u = np.array(vector_u_list)
oned_arr_v = np.array(vector_v_list)

print(oned_arr_u)
print(oned_arr_v)

print(np.array(matrix_A_list))
print(np.array(matrix_B_list))

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [16]:
# Task 2

print(oned_arr_u + oned_arr_v)
print(np.dot(oned_arr_u, oned_arr_v))
print(np.linalg.norm(oned_arr_u))


[5 7 9]
32
3.7416573867739413


In [19]:
# Task 3

print(np.array(matrix_A_list) + np.array(matrix_B_list))
print(np.dot(np.array(matrix_A_list), np.array(matrix_B_list)))
print(np.array(matrix_A_list).transpose())
print(np.linalg.det(np.array(matrix_A_list)))


[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0


In [20]:
# Task 4
print(np.linalg.inv(np.array(matrix_A_list)))
print(np.linalg.solve(np.array(matrix_A_list), np.array([10, 20, 30])))

LinAlgError: Singular matrix